apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    uses: https://github.com/swashbuck1r/workflows/.cloudbees/workflows/build-and-deploy.yaml@reusable
    with:
      project-type: java
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
